### ISSUE TITLE
Instructions resulting in error with "xgb_pred"

### ISSUE THREAD

**Issue by CJones770** [GitDro/DevelopmentalBrainAge#2]
Hello,

Thank you for publishing this! After loading the libraries and model, I tried using the following code (from block 3 of the README):

brain_age_df <-
  xgb_mod %>%
  predict(new_data = your_df)

and received the following error:

Error in xgb_pred(object = object$fit, newdata = new_data) : 
  could not find function "xgb_pred"

I was able to resolve this by using the following:

test_out <- predict(xgb_mod$fit, newdata = as.matrix(your_df))

The estimates look well representative of the ages we expect to derive from our data. Can you please confirm that this is an appropriate way to utilize this package? It seems like the xgb.Booster class is not recognized when using read.RDS() to load the rds file from this repository, which appears to be why adding the "$fit" to the object resolves the issue. R is not my primary language though, so some clarification on whether this is a reasonable way of doing this would be appreciated!

**Comment by GitDro** [comment]
Hey I believe this is a more native xgboost way of generating the predictions, so totally valid. I will copy your code chunk into the readme as other folks might benefit from this as well.
